name: "OPPO Reno Ace  Kernelsu-docker-lxc内核"             
on:
  push:
    branches: ksu 
  schedule:
    - cron: 0 4 * * * 
  workflow_dispatch:                                  
jobs:
  build:
    name: "Build kernel"
    runs-on: ubuntu-latest
    steps:
    - name: Checkout kernel source                  
      uses: actions/checkout@v3.3.0
    - name: Checkout KernelSU
      uses: actions/checkout@v3.3.0
      with:
        repository: tiann/KernelSU
        path: KernelSU
        fetch-depth: 0
    - name: Checkout AnyKernel
      uses: actions/checkout@v3.3.0
      with:
        repository: guh0613/AnyKernel3
        path: zipper
    - name: Android kernel build                    
      uses: guh0613/android-kernel-actions@master
      id: build
      env:
        PYTHON_VERSION: 2
      with:
        arch: arm64                                  
        compiler: clang/10/binutils                               
        defconfig: sm8150-s_defconfig                    
        image: Image-dtb                           
    - name: Upload final output
      uses: actions/upload-artifact@v3.1.2
      with:
        path: zipper/*.zip
